
services:
  clip_trainer:
    container_name: "clip-finetune-container"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./data:/app/data"
      - "./models:/app/models"
    command: [
      "hatch",
      "env",
      "run",
      "python",
      "src/trainer.py",
      "--",
      "--config",
      "config.yaml"
    ]
    ipc: host